Ast <- read.table("/data/rusers/sheddn/UCLA-ASD/plots/DEG-nomito/BA4.6_DEGs-FDR_Ast.txt")
Ast_genes <- row.names(Ast)
Ast_genes <- paste0(Ast_genes, collapse=",")
print(Ast_genes)
write.table(Ast_genes, "/data/rusers/sheddn/UCLA-ASD/plots/DEG-nomito/BA4.6_DEGs-genelist_Ast.txt", sep=',')

Ex <- read.table("/data/rusers/sheddn/UCLA-ASD/plots/DEG-nomito/BA4.6_DEGs-FDR_Ex.txt")
Ex_genes <- row.names(Ex)
Ex_genes <- paste0(Ex_genes, collapse=",")
print(Ex_genes)
write.table(Ex_genes, "/data/rusers/sheddn/UCLA-ASD/plots/DEG-nomito/BA4.6_DEGs-genelist_Ex.txt", sep=',')

In <- read.table("/data/rusers/sheddn/UCLA-ASD/plots/DEG-nomito/BA4.6_DEGs-FDR_In.txt")
In_genes <- row.names(In)
In_genes <- paste0(In_genes, collapse=",")
print(In_genes)
write.table(In_genes, "/data/rusers/sheddn/UCLA-ASD/plots/DEG-nomito/BA4.6_DEGs-genelist_In.txt", sep=',')

Mic <- read.table("/data/rusers/sheddn/UCLA-ASD/plots/DEG-nomito/BA4.6_DEGs-FDR_Mic.txt")
Mic_genes <- row.names(Mic)
Mic_genes <- paste0(Mic_genes, collapse=",")
print(Mic_genes)
write.table(Mic_genes, "/data/rusers/sheddn/UCLA-ASD/plots/DEG-nomito/BA4.6_DEGs-genelist_Mic.txt", sep=',')

Oli <- read.table("/data/rusers/sheddn/UCLA-ASD/plots/DEG-nomito/BA4.6_DEGs-FDR_Oli.txt")
Oli_genes <- row.names(Oli)
Oli_genes <- paste0(Oli_genes, collapse=",")
print(Oli_genes)
write.table(Oli_genes, "/data/rusers/sheddn/UCLA-ASD/plots/DEG-nomito/BA4.6_DEGs-genelist_Oli.txt", sep=',')

OPC <- read.table("/data/rusers/sheddn/UCLA-ASD/plots/DEG-nomito/BA4.6_DEGs-FDR_OPC.txt")
OPC_genes <- row.names(OPC)
OPC_genes <- paste0(OPC_genes, collapse=",")
print(OPC_genes)
write.table(OPC_genes, "/data/rusers/sheddn/UCLA-ASD/plots/DEG-nomito/BA4.6_DEGs-genelist_OPC.txt", sep=',')
